**This is only a basic Mini-Project Template.**
**Delete this note and customize formatting according to your preferences and**
**the Mini-Project instructions. Your document must start the `---` below**
---
title: "Mini-Project 01 - Assessing the Impact of SFFA on Campus Diversity One-Year Later"
author: "jackee101"
editor:
    mode: source
format:
    html:
        code-fold: true
---

## Introduction

In this mini-project, I intend to perform an analysis on the first set of post - SFFA admissions data and pre - SFFA admissions data to see if there were any changes following the decision.

## Data Acquisition and Preparation

Code related to Data Acquisition and Preparation goes here.

Remember that code blocks look like this: 

#' Acquire IPEDS Data for MP#01
#' 
#' This function will acquire and standardize all data for MP#01
#' from IPEDS (https://nces.ed.gov/ipeds/datacenter/DataFiles.aspx)
#' 
#' We're starting in 2010 as the data seems to be reasonably complete 
#' after that point. 

```
acquire_ipeds_data <- function(start_year=2010, end_year=2024){
    library(tidyverse)
    library(glue)
    
    data_dir <- file.path("data", "mp01")
    
    if(!dir.exists(data_dir)){
        dir.create(data_dir, showWarnings=FALSE, recursive=TRUE)
    }
    
    YEARS <- seq(start_year, end_year)
    
    EFA_ALL <- map(YEARS, function(yy){
        if(yy <= 2022){
            ef_url <- glue("https://nces.ed.gov/ipeds/datacenter/data/EF{yy}A.zip")
            
        } else {
            ef_url <- glue("https://nces.ed.gov/ipeds/data-generator?year={yy}&tableName=EF{yy}A&HasRV=0&type=csv")
        }
        
        ef_file <- file.path(data_dir, glue("ef{yy}a.csv.zip"))
        
        if(!file.exists(ef_file)){
            message(glue("Downloading Enrollment Data for {yy} from {ef_url}"))
            download.file(ef_url, destfile = ef_file, quiet=TRUE, mode="wb")    
        }
        
        read_csv(ef_file, 
                 show_col_types=FALSE) |>
            mutate(year = yy, 
                   # American Indian or Alaskan Native
                   enrollment_m_aian = EFAIANM, 
                   enrollment_f_aian = EFAIANW, 
                   # Asian
                   enrollment_m_asia = EFASIAM, 
                   enrollment_f_asia = EFASIAW, 
                   # Black or African-American, 
                   enrollment_m_bkaa = EFBKAAM, 
                   enrollment_f_bkaa = EFBKAAW, 
                   # Hispanic 
                   enrollment_m_hisp = EFHISPM, 
                   enrollment_f_hisp = EFHISPW, 
                   # Native Hawaiian or Other Pacific Islander 
                   enrollment_m_nhpi = EFNHPIM, 
                   enrollment_f_nhpi = EFNHPIW, 
                   # White
                   enrollment_m_whit = EFWHITM, 
                   enrollment_f_whit = EFWHITW, 
                   # Two or More Races
                   enrollment_m_2mor = EF2MORM, 
                   enrollment_f_2mor = EF2MORW, 
                   # Unknown / Undisclosed Race
                   enrollment_m_unkn = EFUNKNM, 
                   enrollment_f_unkn = EFUNKNW, 
                   # US Non-Resident
                   enrollment_m_nral = EFNRALM, 
                   enrollment_f_nral = EFNRALW, 
            ) |> filter(
                (EFALEVEL %in% c(2, 12)) | (LINE %in% c(1, 15))
                # Per 2024 Data Dictionary, 
                # - EFALEVEL 2 = undergrad 
                # - EFALELVE 12 = grad
                # - Line 1 = first year first time full-time undergrad
                # - Line 15 = first year first time part-time undergrad
            ) |> mutate(level = case_when(
                       EFALEVEL == 2 ~ "all undergrad", 
                       EFALEVEL == 12 ~ "all graduate",
                       LINE %in% c(1, 15) ~ "first year undergrad"
                   )
            ) |>
            select(institution_id = UNITID, 
                   year, 
                   level,
                   starts_with("enrollment_")) |>
            group_by(institution_id, 
                     year, 
                     level) |>
            summarize(across(starts_with("enrollment_"), sum), 
                      .groups = "drop")
        
    }) |> bind_rows()
    
    DESC_ALL <- map(YEARS, function(yy){
        if(yy <= 2022){
            hd_url <- glue("https://nces.ed.gov/ipeds/datacenter/data/HD{yy}.zip")
            
        } else {
            hd_url <- glue("https://nces.ed.gov/ipeds/data-generator?year={yy}&tableName=HD{yy}&HasRV=0&type=csv")
        }
        
        hd_file <- file.path(data_dir, glue("hd{yy}.csv.zip"))
        
        if(!file.exists(hd_file)){
            message(glue("Downloading Institutional Descriptions for {yy} from {hd_url}"))
            download.file(hd_url, destfile = hd_file, quiet=TRUE, mode="wb")    
        }
        
        suppressWarnings(
            read_csv(hd_file, 
                 show_col_types=FALSE, 
                 locale=locale(encoding=if_else(yy==2024, "utf-8", "windows-1252"))) |>
            mutate(year = yy, 
                   INSTNM) |> 
            select(institution_id = UNITID, 
                   institution_name = INSTNM, 
                   state = STABBR, 
                   year)
        )
        
    }) |> bind_rows()
    
    inner_join(EFA_ALL, 
               DESC_ALL, 
               join_by(institution_id == institution_id, 
                       year == year))
}

IPEDS <- acquire_ipeds_data()
```

## Exploratory Analysis

Code related to Exploratory Data Analysis goes here. This may include
exploratory graphics, instructor-provided exploratory questions, or other
similar elements. 

## Final Insights and Deliverable

Code related to the final deliverable of the assignment goes here. 



------------------------------------------------------------------------

This work ©2025 by jackee101 was initially prepared as a Mini-Project for
STA 9750 at Baruch College. More details about this course can be found at
[the course site](https://michael-weylandt.com/STA9750) and instructions for
this assignment can be found at 
[MP #01](https://michael-weylandt.com/STA9750/mini/mini01.html)
