---
title: "Mini Project #1 : OP-Ed"
format: pdf
---

On June 29, 2023, the decision for the case of Students for Fair Admissions v. Harvard (SFFA) was handed down by the Supreme Court. This decision caused a ripple in the process of college admissions, as it has disallowed race to be a factor. As the president of CUNY College of Staten Island, I have been following this matter closely. With the release of the first set of post-SFFA admissions data, I'd like to examine the diversity of the student body at my school and to share the effects of the SFFA decision.

I would like to first offer some background on the CUNY College of Staten Island and the definition of diversity I will be using and applying to the school's population. CUNY College of Staten Island is a mid-size CUNY with an average enrollment of around 12977 from 2010 to 2024. With the context of the SFFA case, I will be measuring diversity using the population of non-White and non-Asian American students. I will also be classifying students with two or more races, unknown, unreported, and not a U.S. resident as a non-white and non-Asian American student. For my enrollment rates, from 2010 - 2024, white and Asian American students, on average, make up 60.2% of the enrollment. Non-white and Asian Asian American students, on the other hand, make up 39.8%. 

Starting from 2010, the makeup of the incoming cohorts of first years has been changing. In 2010, white and Asian Americans students made up 64.7% of total first years, while non-white and Asian Americans students only made up 35.3%. This ratio fluctuated throughout the years, and in 2024, white and Asian Americans students made up 51.2% of the total first years. But this 13% decrease is not linear. Upon taking a closer look at the year-by-year comparison of the population, it wildly varies. From 2010-2015, there were 6 years with white and Asian American student populations of less than 50%, and even one year in which it was 38%. This meant that overall, the first-year class has generally been diverse. 

The demographics of the entire student body have a similar trend, where the percentage of white and Asian American students has been decreasing throughout the years. In 2010, white and Asian Americans students made up 71.7% of the total student body, while non-white and Asian Americans students only made up 28.3%. It has been steadily decreasing, with white and Asian Americans students making up 56% of the student body in 2024. However, unlike the first years, this change has been more consistent and gradual. There have been no instances where the white and Asian American population dipped below 50%. The change following the decision was not drastic, with a .01% change in population proportion. 

Although the data from the first years and the overall student body show the proportions of white and Asian Americans students and non-white and Asian Americans students reaching similar proportions, one thing I did not mention earlier was the overall decrease in the population of the student body. From a total enrollment of 13894 in 2010 to an enrollment of 11033 in 2024, the enrollment rate has been shrinking. In 2010, 9959 white and Asian American students enrolled in my school. In 2024, this number shrank by almost 1/3, with the enrollment number being 6183. On the other hand, the enrollment rate of non-white and ASian Americans students has been consistent, with the number being 3935 in 2010 and 4850 in 2024. This begs the question: Is the shifting of the proportions due to the SFFA, or did the proportions shift due to a decrease in enrollment?

In order to get a good view of the bigger picture, I've also decided to select one California public institution to compare against. For this step I selected California State University-Los Angeles. I started with examining the first year cohort which I found extremely different proportions. In 2010 the California institute only had 20.8% of white and Asian Americans students making up their first year cohort. This percentage even went down with the most recent year having only 7.21%. Even when I looked into their overall demographics of the entire student body, the same stands. The white and Asian American students only made up 28.9% of the student body in 2010 and 15% in 2024. The California schools shouldn't have changed their policies at all, with my changes being less than theirs it may mean that the changes in my school's data may be just normal fluctuations. Meaning that the changes may be due to the decrease in enrollments, or just changes in student preferences. Despite the proportion of white and Asian American students decreasing, they still make up predominately the population of the student body. The population of the bourough may come into play as the largest ethnic group in Staten Island is White.i believe that further studies should be done taking in such factors.









